### ISSUE TITLE
Relastionship problem

### ISSUE THREAD

**Issue by djokicpn** [cile1993/cmss#1]
Buraz tebi treba ceo projekat?

**Comment by cile1993** [comment]
> Buraz tebi treba ceo projekat?

ah ne naravno, vecina stvari je resena, klijenti, proizvodi, skladista itd itd... Vec samo ovo sa LOT kodovima...

**Comment by djokicpn** [comment]
ajd pomocicu ti. dodaj me kao contributora

**Comment by cile1993** [comment]
@djokicpn hvala na pomoci, dodao sam

**Comment by djokicpn** [comment]
ovo je onaj crm od poviliasa sto se auto generise?

**Comment by cile1993** [comment]
jeste

**Comment by djokicpn** [comment]
bio sam na sastanku, evo sad cu ti iskucati

**Comment by djokicpn** [comment]
Ovo ti treba, zar ne?
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/16429683/153871206-68174a1b-321f-4868-a644-351c4b3003af.png">

**Comment by djokicpn** [comment]
Ok, push cu ti sada to za koji min, radim trenutno

**Comment by cile1993** [comment]
ma lagano i hvala puno, taman da ispitam kod da naucim nesto

**Comment by djokicpn** [comment]
1. git checkout rework
2. git pull
3. php artisan migrate:fresh
4. php artisan db:seed (or 2 commands in one php artisan migrate:fresh --seed)
5. php artisan serve
@cile1993

**Comment by cile1993** [comment]
Aha lepo je sve kreirano, a ja moram provaliti jos lagano kako cu da prosledim kada das otpremnicu/prijemnicu i lot itd. U svakom slucaju imam primer kako to treba uraditi. Hvala puno

**Comment by djokicpn** [comment]
Dodao sam ti i ovo sto su ti trazili za lot code itd. Da mozes da izvuces item iz warehousa sa svim lot codovima i ukupnom kolicinom

**Comment by djokicpn** [comment]
I samo ako mozes upvote answer na stackoverflow-u :) https://stackoverflow.com/questions/71110494/pivot-tables-with-laravel/71110646#71110646
